### ISSUE TITLE
Mapper wrap fails with nil values

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom#167]
```ruby

ROM.setup(:memory)

class Users < ROM::Relation[:memory]
end

class CreateUser < ROM::Commands::Create[:memory]
  register_as :create
  relation :users
  result :one
end

class UserMapper < ROM::Mapper
  relation :users

  attribute :name
  wrap :last_login do
    attribute :time, from: :last_login_at
    attribute :ip, from: :last_login_ip
  end
end



rom = ROM.finalize.env

rom.command(:users).create.call(name: 'Hannes', last_login_at: Date.today.to_s, last_login_ip: '127.0.0.1')
puts rom.relation(:users).as(:users) # <---- works 

rom.command(:users).create.call(name: 'Hannes', last_login_at: nil, last_login_ip: nil)
puts rom.relation(:users).as(:users) # <---- this blows up due to the nil values in last_login_at and last_login_ip
```

Backtrace:
```
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/hash.rb:12:in `block in <module:Transproc>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `[]'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/hash.rb:21:in `block in <module:Transproc>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `[]'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:16:in `block in compose'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `[]'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/array.rb:7:in `block (2 levels) in <module:Transproc>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/array.rb:7:in `map!'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/array.rb:7:in `block in <module:Transproc>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `[]'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/array.rb:3:in `block in <module:Transproc>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `[]'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-0.6.0.beta1/lib/rom/mapper.rb:86:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-0.6.0.beta1/lib/rom/relation/composite.rb:47:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-0.6.0.beta1/lib/rom/relation/composite.rb:63:in `to_a'
	from /Users/kwando/projects/work/untitled/test.rb:34:in `puts'
	from /Users/kwando/projects/work/untitled/test.rb:34:in `puts'
	from /Users/kwando/projects/work/untitled/test.rb:34:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by kwando** [comment]
Sorry, I missed the first line of the backtrace..
```
/Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/hash.rb:12:in `dup': can't dup NilClass (TypeError)
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/hash.rb:12:in `block in <module:Transproc>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `[]'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/hash.rb:21:in `block in <module:Transproc>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `[]'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:16:in `block in compose'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `[]'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/array.rb:7:in `block (2 levels) in <module:Transproc>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/array.rb:7:in `map!'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/array.rb:7:in `block in <module:Transproc>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `[]'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/array.rb:3:in `block in <module:Transproc>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `[]'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/transproc-0.1.0/lib/transproc/function.rb:11:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-0.6.0.beta1/lib/rom/mapper.rb:86:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-0.6.0.beta1/lib/rom/relation/composite.rb:47:in `call'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-0.6.0.beta1/lib/rom/relation/composite.rb:63:in `to_a'
	from /Users/kwando/projects/work/untitled/test.rb:33:in `puts'
	from /Users/kwando/projects/work/untitled/test.rb:33:in `puts'
	from /Users/kwando/projects/work/untitled/test.rb:33:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by gotar** [comment]
it looks like https://github.com/solnic/transproc bug not rom

**Comment by solnic** [comment]
Yes, seems like transproc assumes it's a non-nil value. I'll fix it there. Thanks for the report.

**Comment by kwando** [comment]
No problemo, just stumbled onto it today =)

**Comment by solnic** [comment]
FYI I fixed it in transproc, here's the output from the repro script in this issue:

``` ruby
{:name=>"Hannes", :last_login=>{:time=>"2015-03-13", :ip=>"127.0.0.1"}}
{:name=>"Hannes", :last_login=>{:time=>"2015-03-13", :ip=>"127.0.0.1"}}
{:name=>"Hannes", :last_login=>{:time=>nil, :ip=>nil}}
```
