### ISSUE TITLE
Default args for relations is broken.

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom#174]
```ruby
class Tickets < ROM::Relation[:sql]
  def by_state(state, limit = 25)
    where(state: state).limit(limit)
  end
end
 
env = setup.finalize
puts env.relation(:tickets).by_state('open').to_a
 
/Users/kwando/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-0.6.0.beta3/lib/rom/relation/curried.rb:33:in `to_a': Tickets#by_state arity is -2 (1 args given) (ArgumentError)
	from /Users/kwando/Desktop/lotus-test/app.rb:40:in `<top (required)>'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/kwando/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require
```

**Comment by solnic** [comment]
seems like `arity` is -2 when there's an arg with a default value, we don't check that yet (we only bail when it's -1). easy fix, if anyone would like to tackle it.

**Comment by solnic** [comment]
it boils down to changing [this](https://github.com/rom-rb/rom/blob/master/lib/rom/relation/lazy.rb#L170) to check for `< 0` and adding a spec example with a default arg.
