### ISSUE TITLE
Undefined method 'acronym' with Rails 3.0.20

### ISSUE THREAD

**Issue by kchien** [rom-rb/rom#272]
I am using Rails 3.0.20 and my Gemfile contains the following rom gems:

```ruby
gem 'rom', '0.7.1'
gem 'rom-rails', '0.3.3'
gem 'rom-yaml', '0.1.0'
``` 

To eliminate the source of the error, I removed all of my ROM related code (mappers, commands) and just tried to run my existing test suite, and I get the error below:

```
/Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/rom-rails-0.3.3/lib/rom/rails/inflections.rb:4:in `block in <top (required)>': undefined method `acronym' for #<ActiveSupport::Inflector::Inflections:0x007ff3c488ee78> (NoMethodError)
from /Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/activesupport-3.0.20/lib/active_support/inflector/inflections.rb:115:in `inflections'
from /Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/rom-rails-0.3.3/lib/rom/rails/inflections.rb:3:in `<top (required)>'
from /Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/backports-3.3.4/lib/backports/tools.rb:328:in `require'
from /Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/backports-3.3.4/lib/backports/tools.rb:328:in `require_with_backports'
from /Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `block in require'
from /Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:227:in `load_dependency'
from /Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require'
from /Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/rom-rails-0.3.3/lib/rom/rails/railtie.rb:3:in `<top (required)>'
from /Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/backports-3.3.4/lib/backports/tools.rb:328:in `require'from /Users/ken/.rbenv/versions/1.9.3-p484/gemsets/my_proj/gems/backports-3.3.4/lib/backports/tools.rb:328:in `require_with_backports'
```

**Comment by AMHOL** [comment]
Yep, looks like the acronym inflection configuration support was only added in ActiveSupport `3.2.5`, could you try adding:

```ruby
gem 'activesupport', '>= 3.2.5' 
```

To your Gemfile, best solution for this is probably just updating the dependency to fit.

**Comment by solnic** [comment]
Actually, we can skip loading that acronym if rails is not new-enough. This shouldn't be something that prevents people from using ROM with Rails.

**Comment by cflipse** [comment]
@kchien should be fixed in 759d5eaa9a22889c84b14b7e4b47c40c26e46b68

**Comment by kchien** [comment]
@cflipse Thanks! :+1:

**Comment by kchien** [comment]
Closing this issue since it's no longer a problem.  However, I made a similar fix in my fork that I didn't push to GitHub, which resulted in the error in issue #274 .
