### ISSUE TITLE
ROM 0.8.1 combine, follow the example but got error

### ISSUE THREAD

**Issue by hotarubi** [rom-rb/rom#292]
I followed the example here to use combine: http://rom-rb.org/guides/basics/mappers/#defining-and-using-mappers
```ruby
require 'rom'
rom = ROM.env
ROM.setup(:memory)
class Items < ROM::Relation[:memory]
end
class Orders < ROM::Relation[:memory]
end
class CreateOrders < ROM::Commands::Create[:memory]
  relation :orders
  register_as :create
end
class CreateItems < ROM::Commands::Create[:memory]
  relation :items
  register_as :create
end
class OrdersWithItemMapper < ROM::Mapper
  relation :orders
  register_as :with_item

  combine :item, on: { food: :food_name } do
    attribute :name, from: :food_name
    attribute(:type) { 'food' }
    attribute :prices
  end
end
ROM.finalize
rom = ROM.env
food_hash = [{ food_name: "Burger", prices: { small: 3.03 } }]
orders_hash = [{ user: "Frank", food: "Burger", size: "small" }]
items = rom.relation(:items)
orders = rom.relation(:orders)
rom.command(:items).create.call food_hash
rom.command(:orders).create.call orders_hash
food_orders = orders.combine(items).as(:with_item)
food_orders.to_a
```

Then I got
```ruby
ArgumentError: wrong number of arguments (1 for 0)
	from /Users/frank.duan/.rvm/gems/ruby-2.1.2/gems/rom-0.8.1/lib/rom/relation/lazy.rb:90:in `call'
	from /Users/frank.duan/.rvm/gems/ruby-2.1.2/gems/rom-0.8.1/lib/rom/relation/graph.rb:89:in `block in call'
	from /Users/frank.duan/.rvm/gems/ruby-2.1.2/gems/rom-0.8.1/lib/rom/relation/graph.rb:89:in `map'
	from /Users/frank.duan/.rvm/gems/ruby-2.1.2/gems/rom-0.8.1/lib/rom/relation/graph.rb:89:in `call'
	from /Users/frank.duan/.rvm/gems/ruby-2.1.2/gems/rom-0.8.1/lib/rom/relation/composite.rb:21:in `call'
	from /Users/frank.duan/.rvm/gems/ruby-2.1.2/gems/rom-0.8.1/lib/rom/relation/materializable.rb:20:in `to_a'
```

Can you help to check if any thing I've done wrong? Many thanks!

**Comment by xaviershay** [comment]
Pretty sure you need a `for_orders` method on the `Items` relation.

See the example in "Combining Tuples from Several Relations" at http://rom-rb.org/guides/basics/mappers/

**Comment by hotarubi** [comment]
Thanks @xaviershay : )

**Comment by solnic** [comment]
FWIW I'm working on a higher-level abstraction to simplify this kind of stuff for all the common use cases - it's called [rom-repository](https://github.com/solnic/rom-repository). Feedback most welcome, will release first alpha in a couple of days.
