### ISSUE TITLE
Curried method silently dropped from query

### ISSUE THREAD

**Issue by backus** [rom-rb/rom#382]
I'm able to call `#to_a` on a relation that contains a curried relation method that has not received all of its arguments.

```ruby
class Tasks < ROM::Relation[:sql]
  def for_user(user_id)
    where(user_id: user_id)
  end
end

class TaskRepo < ROM::Repository[:tasks]
  relations :sub_tasks

  def with_tasks(user_id)
    aggregate(many: sub_tasks).for_user.as(Task).to_a
  end
end
```

In this example, `for_user` is called without arguments and an argument is never supplied before `to_a` is called.

Runnable reproduction:

<details>

```ruby
# frozen_string_literal: true

require 'rom'
require 'rom/sql'
require 'rom/repository'
require 'rom/repository/version'

ROM::VERSION             # => "3.0.1"
ROM::SQL::VERSION        # => "1.0.1"
ROM::Repository::VERSION # => "1.0.2"

class Tasks < ROM::Relation[:sql]
  schema(infer: true) do
    associations do
      belongs_to :user
      has_many   :sub_tasks
    end
  end

  def for_user(user_id)
    where(user_id: user_id)
  end
end

rom =
  ROM.container(:sql, 'sqlite::memory') do |conf|
    conf.gateways[:default].use_logger(Logger.new(STDOUT))

    conf.default.create_table(:users) do
      primary_key :id
      column :name, String, null: false
      column :email, String, null: false
    end

    conf.default.create_table(:tasks) do
      primary_key :id
      foreign_key :user_id, :users
      column :title, String, null: false
    end

    conf.default.create_table(:sub_tasks) do
      primary_key :id
      foreign_key :task_id, :tasks
      column :title, String, null: false
    end

    conf.relation(:users) do
      schema(infer: true) do
        associations do
          has_many :tasks
        end
      end
    end

    conf.register_relation(Tasks)
  end

class SubTask < Dry::Struct::Value
  attribute :id, Dry::Types['strict.int']
  attribute :task_id, Dry::Types['strict.int']
  attribute :title, Dry::Types['strict.string']
end

class Task < Dry::Struct::Value
  attribute :id, Dry::Types['strict.int']
  attribute :user_id, Dry::Types['strict.int']
  attribute :title, Dry::Types['strict.string']
  attribute :sub_tasks,   Dry::Types['strict.array'].member(SubTask)
end

class User < Dry::Struct::Value
  attribute :id,      Dry::Types['strict.int']
  attribute :user_id, Dry::Types['strict.int']
  attribute :title,   Dry::Types['strict.string']
  attribute :tasks,   Dry::Types['strict.array'].member(Task)
end

class TaskRepo < ROM::Repository[:tasks]
  relations :sub_tasks

  def with_tasks(user_id)
    aggregate(many: sub_tasks).for_user.as(Task).to_a
  end
end

rom.relations.users.insert(id: 1, name: 'John', email: 'john@example.com')
rom.relations.tasks.insert(user_id: 1, title: 'Learn ROM')
rom.relations.sub_tasks.insert(task_id: 1, title: 'Read docs')
rom.relations.sub_tasks.insert(task_id: 1, title: 'Fiddle')
rom.relations.sub_tasks.insert(task_id: 1, title: 'Ask questions in gitter')

rom.relations.users.insert(name: 'Jim', email: 'jim@example.com')
rom.relations.tasks.insert(user_id: 2, title: 'Find bugs')
rom.relations.sub_tasks.insert(task_id: 2, title: 'Fiddle')

puts

repo = TaskRepo.new(rom)

p repo.with_tasks(1)
# >> [#<Task id=1 user_id=1 title="Learn ROM" sub_tasks=[#<SubTask id=1 task_id=1 title="Read docs">, #<SubTask id=2 task_id=1 title="Fiddle">, #<SubTask id=3 task_id=1 title="Ask questions in gitter">]>, #<Task id=2 user_id=2 title="Find bugs" sub_tasks=[#<SubTask id=4 task_id=2 title="Fiddle">]>]
```

</details>

**Comment by solnic** [comment]
Thanks for reporting this. I'll fix it in next version. I'm curious to know how you ended up with this?

**Comment by backus** [comment]
I was running [`mutest`](https://github.com/backus/mutest) on my Repository and noticed saw that it let me drop the argument. Didn't intend to actually use it this way

**Comment by solnic** [comment]
Hah fantastic :) I'll fix, thanks again

**Comment by solnic** [comment]
This now raises:

```
/Users/solnic/Workspace/rom-rb/rom/lib/rom/relation/curried.rb:42:in `call': curried Tasks#for_user relation was called without any arguments (ArgumentError)
        from /Users/solnic/Workspace/rom-rb/rom/lib/rom/relation/graph.rb:90:in `call'
        from /Users/solnic/Workspace/rom-rb/rom/lib/rom/relation/composite.rb:21:in `call'
        from /Users/solnic/Workspace/rom-rb/rom-repository/lib/rom/repository/relation_proxy.rb:51:in `call'
        from /Users/solnic/Workspace/rom-rb/rom/lib/rom/relation/materializable.rb:20:in `to_a'
        from tmp/repros/382.rb:82:in `with_tasks'
```
