### ISSUE TITLE
Schema's :timestamp plugin broken with rom-sql

### ISSUE THREAD

**Issue by cmavromoustakos** [rom-rb/rom#460]
I recently upgraded to: `rom-core-4.0.0` and `rom-sql-2.0.0` from `rom (3.3.0)` and `rom-sql (1.3.3)` and started getting the error show below. 

The line that seems to be causing the exception is:

```
 class Persistence::Relations::Users < ROM::Relation[:sql]
 ┆ schema(:identity_providers, infer: true) do
 ┆ ┆ use :timestamps
 ┆ end

```

```
NoMethodError: undefined method `indexed?' for #<ROM::Attribute:0x007fbed5e9a5e8>
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/attribute.rb:423:in `method_missing'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-sql-2.0.0/lib/rom/sql/schema/inferrer.rb:122:in `mark_indexed'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-sql-2.0.0/lib/rom/sql/schema/inferrer.rb:51:in `block in infer_from_database'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-sql-2.0.0/lib/rom/sql/schema/inferrer.rb:51:in `map'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-sql-2.0.0/lib/rom/sql/schema/inferrer.rb:51:in `infer_from_database'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-sql-2.0.0/lib/rom/sql/schema/inferrer.rb:35:in `call'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/schema.rb:361:in `finalize_attributes!'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-sql-2.0.0/lib/rom/sql/schema.rb:146:in `finalize_attributes!'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/schema.rb:56:in `block in <class:Schema>'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/support/notifications.rb:131:in `trigger'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/support/notifications.rb:69:in `block in trigger'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/support/notifications.rb:68:in `each'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/support/notifications.rb:68:in `trigger'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/setup/finalize/finalize_relations.rb:82:in `build_relation'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/setup/finalize/finalize_relations.rb:48:in `block (2 levels) in run!'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/setup/finalize/finalize_relations.rb:31:in `each'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/setup/finalize/finalize_relations.rb:31:in `block in run!'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/relation_registry.rb:9:in `initialize'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/registry.rb:27:in `new'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/registry.rb:27:in `new'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/setup/finalize/finalize_relations.rb:30:in `run!'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/setup/finalize.rb:86:in `load_relations'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/setup/finalize.rb:62:in `run!'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/create_container.rb:38:in `finalize'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/create_container.rb:14:in `initialize'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/create_container.rb:59:in `initialize'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/create_container.rb:65:in `new'
/Users/cmavromoustakos/.rvm/gems/ruby-2.4.1/gems/rom-core-4.0.0/lib/rom/create_container.rb:65:in `container'
/Users/cmavromoustakos/Documents/Sandbox/indie-ninja-api/lib/indie_ninja/api/persistence.rb:40:in `container'
```

**Comment by solnic** [comment]
@flash-gordon could you take a look?

**Comment by v-kolesnikov** [comment]
I can assume that it was here: https://github.com/rom-rb/rom/commit/c7518fc28#diff-3ac454f9c196d0f7c33922c20f51583cL117

`attr_class` must be passed to schema constructor, elsewhere schema will be initialized with `ROM::Attribute` which has not `indexed?` method.

@flash-gordon What do you think?

**Comment by solnic** [comment]
@cmavromoustakos btw this schema plugin only adds attributes, they **do not set default values**, I believe you wanted to have something that deals with actually setting timestamp values by default. If that's the case, `Changeset` + `:add_timestamp` and/or `:touch` is what you need.

**Comment by solnic** [comment]
Fixed via https://github.com/rom-rb/rom/pull/464/files
