### ISSUE TITLE
timestamp plugin breaks with changesets

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#475]
Using a changeset in combination with a custom command using the `timestamps` plugin results in an error:

```ruby
require 'bundler/inline'

gemfile(install: true) do
  source "http://rubygems.org"

  gem 'rom'
  gem 'rom-sql'
  gem 'sqlite3'
end


class Users < ROM::Relation[:sql]
  schema(infer: true)
end

class CreateUser < ROM::Commands::Create[:sql]
  relation :users
  register_as :create

  use :timestamps
  timestamp :created_at, :updated_at
end

rom = ROM.container(:sql, "sqlite::memory") do |conf|

  conf.default.create_table :users do
    primary_key :id
    column :name, String, null: false
    column :created_at, DateTime, null: false
    column :updated_at, DateTime, null: false
  end

  conf.register_relation(Users)
  conf.register_command(CreateUser)

end

rom.commands[:users].create.call(name: 'Test User one')

puts rom.relations[:users].to_a

rom.relations[:users].changeset(:create, name: 'Test User two').commit

puts rom.relations[:users].to_a
```

results in: 
```
{:id=>1, :name=>"Test User one", :created_at=>2017-12-28 18:48:28 -0500, :updated_at=>2017-12-28 18:48:28 -0500}
/home/flip/.gem/ruby/2.4.1/gems/rom-sql-2.3.0/lib/rom/sql/commands/create.rb:22:in `execute': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from /home/flip/.gem/ruby/2.4.1/gems/rom-core-4.1.0/lib/rom/command.rb:280:in `call'
	from /home/flip/.gem/ruby/2.4.1/gems/rom-sql-2.3.0/lib/rom/sql/commands/error_wrapper.rb:16:in `call'
	from /home/flip/.gem/ruby/2.4.1/gems/rom-core-4.1.0/lib/rom/commands/composite.rb:17:in `call'
	from /home/flip/.gem/ruby/2.4.1/gems/rom-changeset-1.0.1/lib/rom/changeset/stateful.rb:201:in `commit'
	from ./rom-repo.rb:42:in `<main>'
```

**Comment by cflipse** [comment]
it appears that the error comes in the `apply_hooks` method https://github.com/rom-rb/rom/blob/master/core/lib/rom/command.rb#L276-L278

The command call returns a merged tuple with timestamps set; the changeset returns `nil`
