### ISSUE TITLE
Tests are broken - cannot load such file -- rom/version

### ISSUE THREAD

**Issue by DNNX** [rom-rb/rom#560]
**Describe the bug**

If I follow instructions from the readme on how to run tests, they all fail with `cannot load such file -- rom/version`. I see the same error happens on Travis - the last build is red because of it.

**To Reproduce**

```
docker-compose run --rm gem "bundle && rspec"
```

It will produce a wall of text, the top of which is

```
...
Bundle complete! 14 Gemfile dependencies, 40 gems now installed.
Bundled gems are installed into `/usr/local/bundle`

An error occurred while loading ./spec/spec_helper.
Failure/Error: require 'rom/core'

LoadError:
  cannot load such file -- rom/version
# /usr/local/bundle/gems/rom-core-5.1.0/lib/rom/core.rb:6:in `require'
# /usr/local/bundle/gems/rom-core-5.1.0/lib/rom/core.rb:6:in `<top (required)>'
# ./lib/rom/sql.rb:3:in `require'
# ./lib/rom/sql.rb:3:in `<top (required)>'
# ./lib/rom-sql.rb:1:in `require'
# ./lib/rom-sql.rb:1:in `<top (required)>'
```

I did a git bisect and found which commit breaks it.

```
52f189ec6073272c659ed352d22cecf72c8142fc is the first bad commit
commit 52f189ec6073272c659ed352d22cecf72c8142fc
Author: Piotr Solnica <piotr.solnica@gmail.com>
Date:   Wed Apr 24 11:02:00 2019 +0200

    Use released rom dependencies

:100644 100644 d84bdb4d593cbdb17c22fd526c2392ba8924b087 20d9d5761f546e344a4f47fa8c8c9d6d655519b4 M	Gemfile
```

Probably, what really happens is that it's not that 52f189ec6073272c659ed352d22cecf72c8142fc broke it, but probably some other changes in the rom itself.

**Expected behavior**

Green tests.

**Your environment**

- Affects my production application: **NO**
- Ruby version: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
- OS: 
```
root@1766b313384b:/gem# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by solnic** [comment]
This was fixed via a18347d0251ab7a87d181ca9c5401b2ac1aee31c
