### ISSUE TITLE
Relation doesn't work in repository

### ISSUE THREAD

**Issue by nagamine-git** [rom-rb/rom#668]
## Describe the bug

When I was tried the tutorial, but it didn't work.
https://rom-rb.org/5.0/learn/repositories/reading-aggregates/#relation-schema

## To Reproduce
demo.rb
```ruby
require 'rom'
require 'rom/repository' # I added this line

rom = ROM.container(:sql, 'sqlite::memory') do |conf|
  conf.default.create_table(:users) do
    primary_key :id
    column :name, String, null: false
    column :email, String, null: false
  end

  conf.default.create_table(:tasks) do
    primary_key :id
    foreign_key :user_id, :users
    column :title, String, null: false
  end

  conf.relation(:users) do
    schema(infer: true) do
      associations do
        has_many :tasks
      end
    end
  end

  conf.relation(:tasks) do
    schema(infer: true) do
      associations do
        belongs_to :user
      end
    end
  end
end


class UserRepo < ROM::Repository[:users]
  def user_with_tasks
    users.combine(:tasks)
  end
end


user_repo = UserRepo.new(rom)

user_repo.user_with_tasks.one
```

```
irb(main):047:0> load './demo.rb'
Traceback (most recent call last):
       15: from /usr/local/bin/irb:23:in `<main>'
       14: from /usr/local/bin/irb:23:in `load'
       13: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
       12: from (irb):46
       11: from (irb):47:in `rescue in irb_binding'
       10: from (irb):47:in `load'
        9: from /app/hanami_console.rb:127:in `<top (required)>'
        8: from /app/hanami_console.rb:120:in `user_with_tasks'
        7: from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:59:in `combine'
        6: from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:59:in `each'
        5: from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:86:in `block in combine'
        4: from /usr/local/bundle/gems/rom-repository-1.4.0/lib/rom/repository/relation_proxy/combine.rb:255:in `combine_opts_for_assoc'
        3: from /usr/local/bundle/gems/rom-3.3.3/lib/rom/registry.rb:32:in `fetch'
        2: from /usr/local/bundle/gems/rom-3.3.3/lib/rom/registry.rb:32:in `fetch'
        1: from /usr/local/bundle/gems/rom-3.3.3/lib/rom/registry.rb:35:in `block in fetch'
ROM::Registry::ElementNotFoundError (:tasks doesn't exist in ROM::RelationRegistry registry)
```

## Expected behavior

I hope the result same as the tutorial.

## My environment

- Affects my production application: NO
- Ruby version: 2.7.5
- Environment: Docker(image: ruby:2.7.5-slim)

**Comment by solnic** [comment]
You used rom 3 and the tutorial is for rom 5. Please try with the correct version, it should work just fine.

**Comment by nagamine-git** [comment]
Thank you for your prompt reply. I was wrong.
