### ISSUE TITLE
ROM::NoRelationError, `method_missing': undefined relation :to_ary

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom#80]
```ruby
setup.relation(:order_rows)
setup.relation(:orders) do
  one_to_many(:order_rows, key: :order_id)

  def with_rows
    association_join(:order_rows, select: [:id, :product_id, :quantity])
  end

  def by_status(status)
    where(status: status)
  end
end

setup.mappers do
  define(:orders) do
    model name: 'Order'

    wrap :customer do
      model Order::Customer
      attribute :name
      attribute :email
      attribute :phone
    end

    group :rows do
      attribute :id, from: :order_rows_id
      attribute :product_id
      attribute :quantity
    end
  end

end

rom = setup.finalize

puts rom.read(:orders).by_status('accepted')
```
This fails with the following error:
```
/Users/kwando/projects/gems/test-rom/vendor/bundle/ruby/2.2.0/gems/rom-0.5.0/lib/rom/reader.rb:111:in `method_missing': undefined relation :to_ary within "orders.by_status" (ROM::NoRelationError)
        from sms_test.rb:99:in `puts'
        from sms_test.rb:99:in `puts'
        from sms_test.rb:99:in `<main>'
```
I think ```puts``` is doing some magic in order to print this stuff.. though it breaks rom in a non obvious way.

**Comment by solnic** [comment]
Thanks for reporting. That's weird, reader is an enumerable and it implements each so I would expect this to work. I will look into it.

**Comment by solnic** [comment]
OK I guess I need to `alias_method :to_ary, :to_a` there. Fix, or rather new feature, is coming in...;)

**Comment by kwando** [comment]
Goodie =)
