### ISSUE TITLE
Raise some kind of error on reserved repository names

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom#82]
```ruby
setup = ROM.setup(database: 'mysql2://<connection details>')
setup.database.use_logger(LOGGER)
```
This blows up with the following error:
```
/Users/kwando/projects/gems/test-rom/vendor/bundle/ruby/2.2.0/gems/rom-0.5.0/lib/rom/adapter.rb:97:in `block in []': undefined method `to_sym' for nil:NilClass (NoMethodError)
        from /Users/kwando/projects/gems/test-rom/vendor/bundle/ruby/2.2.0/gems/rom-0.5.0/lib/rom/adapter.rb:97:in `each'
        from /Users/kwando/projects/gems/test-rom/vendor/bundle/ruby/2.2.0/gems/rom-0.5.0/lib/rom/adapter.rb:97:in `detect'
        from /Users/kwando/projects/gems/test-rom/vendor/bundle/ruby/2.2.0/gems/rom-0.5.0/lib/rom/adapter.rb:97:in `[]'
        from /Users/kwando/projects/gems/test-rom/vendor/bundle/ruby/2.2.0/gems/rom-0.5.0/lib/rom/config.rb:39:in `build'
        from /Users/kwando/projects/gems/test-rom/vendor/bundle/ruby/2.2.0/gems/rom-0.5.0/lib/rom/global.rb:37:in `setup'
        from sms_test.rb:9:in `<main>'
```

**Comment by solnic** [comment]
This is a nasty gotcha where config-parsing class thinks "database" key means it's a hash coming from a database.yml file. This needs to be improved so that a user gets a nice error message that "database" is a reserved key.

**Comment by aflatter** [comment]
@solnic: Please correct me if I'm wrong.

`ROM::Config` is being moved to rom-rails as part of rom-rb/rom-rails#16, so ROM will only support the following two formats:

```ruby
ROM.setup(database: 'mysql2://foo')
ROM.setup(database: {uri: 'mysql2://foo', options: {foo: 'bar'}})
```

`:database` will not be a reserved key after the change.

**Comment by solnic** [comment]
@aflatter add `ROM.setup('mysql://foo')` to the list and then I can say "yes, correct" :)

**Comment by solnic** [comment]
This is now fixed along with a new syntax:

``` ruby
# this will work
setup = ROM.setup(database: [:sql, 'mysql2://localhost'])
```
